[app]
name="demo"
host="0.0.0.0"
port="8000"
key="this is your app key"

[mysql]
host="127.0.0.1"
port="3306"
username="cloud_name"
password="123456"
database="cloud_station"

[log]
level="debug"
format="text"
to="stdout"
path_dir="logs"
